#!/bin/bash
set +x
set -e


# get the required resources
echo "Installing necessary resources"
pip install Flask tensorflow nltk
python3 -c "import nltk; nltk.download('punkt')"

# then start the app
echo "Starting the app"
python3 app.py